### PR TITLE
Feature: Script 1

### PR DESCRIPTION
**Pull request by sarahquinn-kainos**
1. create a directory structure in the ~/team/folders/{foldername}
within {foldername}, a file with {filename}. Contents cannot be empty but is up to you.
error handling - helpful messages. If folder and file already exists, cancel

### CODE REVIEW

**Comment by peterjgordon** [comment]
* When the file and folder already exists, a message should be printed and the program should exit.
* `mkdir: cannot create directory ‘team’: File exists` this shouldn't appear, it needs error checking.
* Not specifying a parameter should print an informative message.

**Comment by peterjgordon** [comment]
Folder name should be the first parameter, File name should be a separate parameter.
/team/folders/**folder** or /team/folders/**folderCat** cannot be created at the same time.

**Comment by peterjgordon** [comment]
I recommend the following format for the invalid parameter count message:
`x/2 arguments provided: script1.sh <folder> <file>`

**Comment by squinnie** [comment]
* code looks good to me - finished

**Review by peterjgordon — APPROVED** [review]
Looks good to me!

**Pull request merged**
